### PR TITLE
[FEATURE] Two-way sync between rows and model

### PR DESCRIPTION
**Pull request by offirgolan**
This PR allows the user to have a two-way sync between the table's row content and their passed in model instance without modifying the existing API.

Usage:

```js
new Table(this.get('columns'), this.get('model'), { enableSync: true });
```

If you want `enableSync` to be enabled by default, add the following to your __config/environment.js__ file

```js
module.exports = function(environment) {
  var ENV = {
   // ...
    'ember-light-table': {
      enableSync: true
    }
  };
  
  // ...

  return ENV;
};
```

### CODE REVIEW

**Comment by taras** [comment]
LGTM 👍

**Comment by sivakumar-kailasam** [comment]
@offirgolan Can we get a release for this? Much awaited feature 😄

**Comment by offirgolan** [comment]
@sivakumar-kailasam waiting for #177! Once that's merged, I'll make a new minor release.

**Comment by JensNordenbro** [comment]
@offirgolan - Is this part of 1.8.3 release?

**Pull request merged**
