### PR TITLE
Update ember-cli-changelog

### PR DESCRIPTION
**Pull request by Gaurav0**

### CODE REVIEW

**Comment by alexander-alvarez** [comment]
Hi. Thanks for submitting a PR. Would you like to explain why is this needed?

**Comment by Gaurav0** [comment]
Mostly it gets rid of several warnings on build.

**Comment by alexander-alvarez** [comment]
Can you be more specific? You're changing a third party dev dependency to one under an organization who's source code you haven't linked.

Given recent npm events, I feel more info is necessary

**Comment by Gaurav0** [comment]
I've done so. Been waiting.

**Comment by rwwagner90** [comment]
Why do we need it published at all here guys? We can use the tag from github no problem

**Comment by Gaurav0** [comment]
Github tags can be deleted and even assigned to a different commit, but if that's ok with @alexander-alvarez , it's ok with me, since it's only a devDependency and it won't hit my app. Opened a PR that way: #651

**Pull request closed without merging**
