### PR TITLE
Add cookbook index

### LINKED ISSUE #443: Add `cookbook.index` route to dummy app
#441 introduces a link to https://offirgolan.github.io/ember-light-table/#/cookbook, but there's no index route yet.

A simple but neat list and maybe a few explanatory paragraphs will do just fine.

### PR DESCRIPTION
**Pull request by bravo-kernel**
Closes #443.

- [x] add index route
- [x] add description list
- [x] sort items alphabetically
- [x] consistent naming
- [x] add descriptions

### CODE REVIEW

**Comment by bravo-kernel** [comment]
Proposed solution:
image

**Comment by bravo-kernel** [comment]
Failing tests seem unrelated as tests run fine locally and other PRs are failing at the same location. 

Is this a known issue?

**Comment by bravo-kernel** [comment]
**Final concept:**

image

**Comment by bravo-kernel** [comment]
Squashed and ready to merge unless.... you would like to see some changes.

**Comment by buschtoens** [comment]
Looks slick! Thank you :)

Two minor suggestions:

The primary idea of occlusion rendering is to only render the DOM nodes that are currently in the visible viewport. With the traditional infinity-scroll setup, ELT tend to get really slow the longer you scroll down, since we're continuously adding more and more rows. Occlusion rendering (enabled through [vertical-collection](https://github.com/html-next/vertical-collection/)) removes rows you've scrolled past, so we're only ever rendering as many rows as are currently visible. This means you can really keep on scrolling forever, without degrading performance.

ELT is a popular addon and so is often used by devs who are new to Ember. They might not know the term "the Ember way". Maybe change it to:

> Interact with your rows and cells the Ember way: "Data Down, Actions Up" (DDAU)

**Comment by bravo-kernel** [comment]
Awesome suggestions and exactly for the two points I was having doubts about (as an Ember starter myself). I will update accordingly.

**Comment by bravo-kernel** [comment]
Updated as requested :shipit:

**Pull request closed without merging**
