### PR TITLE
update dependencies

### PR DESCRIPTION
**Pull request by bekzod**

### CODE REVIEW

**Comment by snewcomer** [comment]
@bekzod What do you think about updating the travis config as well?  Perhaps ember-try back to 2.16?

**Comment by snewcomer** [comment]
Updating travis will allow deps to use classes as well.  2.12 fails Ref #674

**Comment by snewcomer** [comment]
@fran-worley Any thoughts on this PR?  I could bump the travis config post merge

**Comment by fran-worley** [comment]
@snewcomer thanks for the ping - we should bump the ember-concurrency dependency as I think we're on 10 or 11 (maybe even 12 now!) Can we double check other dependencies as we may aswell get this right at the point of merging.

In terms of ember try/ travis, we should ensure that we're testing against all 'supported' ember versions and for the master branch I believe this goes back to ember 2.13.

I'm not entirely convinced about bumping ember js quite so high on master branch as the deprecations being thrown up by ember are only being fixed in the 2.x branch.

I suggest we bump the ember version to the point at which the deprecations start getting noisy on master branch and then raise a further PR against 2.x branch to update ember to latest version. Again, updating ember try/ travis to test all 'supported' versions.

**Comment by fran-worley** [comment]
May also be worth updating the readme to point people using ember >3? to the v2.x branch.

**Comment by bekzod** [comment]
sorry for missing, you seem handled everything shout if you need me

**Comment by fran-worley** [comment]
Closing in favour of #693 thanks @bekzod I've taken this into a new PR to finish this off.

**Pull request closed without merging**
