### PR TITLE
replace `sendAction` with modern callable methods

### LINKED ISSUE #587: sendAction deprecation warning
When using the library I'm getting the following warnings

`sendAction("onBeforeResponsiveChange")`
`sendAction("onAfterResponsiveChange")`

`Component#sendAction is deprecated. Please use closure actions instead. [deprecation id: ember-component.send-action]`

I'm using
ember-light-table 1.13.2
ember-cli 3.4.1

### PR DESCRIPTION
**Pull request by donaldwasserman**
This fixes #587.

CC: @buschtoens

### CODE REVIEW

**Comment by alexander-alvarez** [comment]
@donaldwasserman  Awesome. Thanks for this.

I think this might technically be a breaking change since it prevents the superfluous bubbling up of events of ember yore, which maybe someone is unwittingly relying on. Either way, LGTM -- need to remember to do a major version bump though. Thoughts @buschtoens

**Comment by donaldwasserman** [comment]
@alexander-alvarez Thanks for taking a look at this.

On one hand it seems sort of silly to do a major version bump for this, on the other, there is likely > 0 apps still bubbling actions, I'm sure. 

I'd still like to get rid of the jQuery stuff (see #591 ) so maybe we could wrap that + any other big ticket items up into a separate branch for now.

**Comment by alexander-alvarez** [comment]
Yeah -- Sounds good to me. :ok_hand:

I made a branch for the 2.x stuff https://github.com/offirgolan/ember-light-table/tree/2-x if you want to change the base. And we can publish betas from there so you can use them

**Comment by donaldwasserman** [comment]
Sounds good - I'm going to be on vacation next week, but I'm trying to get jQuery out of our app and this is one of the last big pieces that uses it. 

So hopefully I can get that piece done shortly. 

Thanks for the help!

**Comment by HenryVonfire** [comment]
@alexander-alvarez is there anything else left to merge this PR and publish a beta version?

PS. the Readme in npm still points to slack instead of discord

**Comment by alexander-alvarez** [comment]
@HenryVonfire  @donaldwasserman 
published under `ember-light-table@2.0.0-beta.0` and `ember-light-table@next`

**Comment by fran-worley** [comment]
@HenryVonfire are you sure you got them all in this MR? I've updated to 2.0.0-beta.0 and I'm still getting a warning from `onScrolledToBottom()`

**Comment by fran-worley** [comment]
It looks like this MR didn't actually make the release https://github.com/offirgolan/ember-light-table/commits/v2.0.0-beta.0

**Comment by HenryVonfire** [comment]
@alexander-alvarez seems that `ember-light-table@2.0.0-beta.0` and `ember-light-table@next` are still based on master

**Comment by fran-worley** [comment]
@alexander-alvarez seems like beta.1 has got it covered, thanks for the quick fix!

**Comment by MichalBryxi** [comment]
I believe there are some instances of `sendAction` that you probably missed: https://github.com/offirgolan/ember-light-table/blob/2-x/addon/mixins/table-header.js#L181

Maybe they are not intended to be in use, but I'm basically copy-pasting the examples from your guides and stubled upon this. I'm using your `@next` branch that points me to `2.0.0-beta.2`

**Pull request merged**
