### PR TITLE
Remove jQuery usage

### LINKED ISSUE #591: Remove jQuery
This really isn't an issue _per se_, but more of a question: Would @buschtoens be ok with a PR removing jQuery?

It looks like it's only used in a few spots: 

- Managing some mouse event listeners in `lt-column-resizer`
- Getting some various widths (`.width()`, `.outerWidth()`)
- Class toggling
- Parent/Closest dom traversal
- Outdated blueprint code

 The only someone tricky thing is the usage of the `.closest` and the computed `$column` property used in [lt-column-resizer](https://github.com/offirgolan/ember-light-table/blob/master/addon/components/lt-column-resizer.js#L18)

I'd be happy to do this, just wanted to make sure I wasn't missing any sort of big ticket issues.

### PR DESCRIPTION
**Pull request by donaldwasserman**
Fixes #591

CC: @alexander-alvarez I left usage of `this.$().text().trim` in the test blueprint. I'm going to make a seperate PR for updating ember + friends so we can get qunit dom working.

I'm also going to make a PR against ember-scrollable to remove that little bit of jQuery as well.

### CODE REVIEW

**Comment by alexander-alvarez** [comment]
@donaldwasserman  LGTM! Thanks so much for taking the initiative on this :clap:

**Comment by alexander-alvarez** [comment]
Released as `ember-light-table@2.0.0-beta.2` and `ember-light-table@next`

**Comment by donaldwasserman** [comment]
Happy to help - I’m working on the ember-scrollable piece right now. Hopefully have that done this week. Maybe you know someone who can get that merged in 😜

Do you know of anything else that uses jQuery in here?

**Comment by alexander-alvarez** [comment]
> Maybe you know someone who can get that merged in
Yup, I can do that for you when it's ready. I'm trying to get out of your way as much as possible

I don't think there is any, but we should be able to do a jquery-less build and if tests pass then :+1: 
maybe rip-off
https://github.com/cibernox/ember-power-select/blob/master/config/ember-try.js
https://github.com/emberjs/ember-optional-features

**Pull request merged**
