### PR TITLE
Upgrade ember-scrollable

### LINKED ISSUE #568: Deprecation warning when `ember s`
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: bai-ui -> ember-light-table -> ember-in-viewport -> ember-cli-babel
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: bai-ui -> ember-light-table -> ember-in-viewport -> ember-getowner-polyfill -> ember-cli-babel
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: bai-ui -> ember-light-table -> ember-scrollable -> ember-component-inbound-actions -> ember-cli-babel
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: bai-ui -> ember-light-table -> ember-scrollable -> ember-element-resize-detector -> ember-cli-babel

"ember-light-table": "^1.12.2",
"ember-cli": "^3.1.4",

### PR DESCRIPTION
**Pull request by Gaurav0**
Fixes #568

### CODE REVIEW

**Comment by jrjohnson** [comment]
Yes please!

**Comment by alexander-alvarez** [comment]
LGTM :+1:

**Comment by lsg-richard** [comment]
Would it be possible to have a new release with this in?

**Comment by Gaurav0** [comment]
@alexander-alvarez @buschtoens ^^

**Pull request merged**
